handle flags and skip comments when parsing requirements.txt
beam-cloud/beta9 pull request #425
Opened 2024-08-03 20:12 UTC by dleviminzi

We need to handle flag lines in requirements.txt differently and we should remove comment lines as well.

2024-08-03 21:38 UTC, luke-lombardi requested changes
Do you mind adding some examples of what the edge cases you're handling here are?

2024-08-03 21:42 UTC, mernit commented
> Do you mind adding some examples of what the edge cases you're handling here are?

@luke-lombardi 

```
--extra-index-url https://download.pytorch.org/whl/cu121
torch==2.2.1+cu121
torchaudio==2.2.1+cu121
torchvision==0.17.1+cu121
onnxruntime-gpu==1.17.1
diffusers==0.27.0
transformers==4.37.1
accelerate==0.28.0
insightface==0.7.3
deepface==0.0.87
safetensors==0.4.2
spaces==0.19.4
omegaconf==2.3.0
huggingface-hub==0.20.2
opencv-python==4.9.0.80
Cython==3.0.9
cmake==3.28.3
gdown==5.1.0
peft==0.9.0
boto3==1.34.71
scipy==1.13.0
einops==0.7.0
torchsde==0.2.6
ultralytics==8.2.26 
```

2024-08-04 13:26 UTC, dleviminzi commented
> > Do you mind adding some examples of what the edge cases you're handling here are?
> 
> 
> 
> @luke-lombardi 
> 
> 
> 
> ```
> 
> --extra-index-url https://download.pytorch.org/whl/cu121
> 
> torch==2.2.1+cu121
> 
> torchaudio==2.2.1+cu121
> 
> torchvision==0.17.1+cu121
> 
> onnxruntime-gpu==1.17.1
> 
> diffusers==0.27.0
> 
> transformers==4.37.1
> 
> accelerate==0.28.0
> 
> insightface==0.7.3
> 
> deepface==0.0.87
> 
> safetensors==0.4.2
> 
> spaces==0.19.4
> 
> omegaconf==2.3.0
> 
> huggingface-hub==0.20.2
> 
> opencv-python==4.9.0.80
> 
> Cython==3.0.9
> 
> cmake==3.28.3
> 
> gdown==5.1.0
> 
> peft==0.9.0
> 
> boto3==1.34.71
> 
> scipy==1.13.0
> 
> einops==0.7.0
> 
> torchsde==0.2.6
> 
> ultralytics==8.2.26 
> 
> ```

The issue is that any line with a flag in requirements.txt has the space removed in the sanitize method. Also, if there is a comment in the file, no packages after it will actually get installed. This change filters out comments and parses flags correctly. 

In the example above --extra-index-url https://download.pytorch.org/whl/cu121 would become --extra-index-urlhttps://download.pytorch.org/whl/cu121

2024-08-04 14:39 UTC, luke-lombardi approved these changes

2024-08-05 13:42 UTC, merged