Check gpu limit before creating stub
beam-cloud/beta9 pull request #487
Opened 2024-08-27 16:20 UTC by dleviminzi

This PR adds a check to `GetOrCreateStub` that ensures that the user has a valid GPU limit if they've requested to create a stub that includes a GPU.

2024-08-28 19:20 UTC, luke-lombardi requested changes
just one comment and good to merge

2024-08-28 19:20 UTC, luke-lombardi commented on pkg/gateway/services/stub.go
> +				ErrMsg: "GPU concurrency limit is 0. A payment method is required to deploy with GPUs.",
Since this in beta9, and there's no concept of "payment", I would just let the error be the first part of that message.

2024-08-29 20:40 UTC, luke-lombardi approved these changes

2024-08-29 20:59 UTC, jsun-m approved these changes

2024-08-29 21:17 UTC, luke-lombardi approved these changes

2024-08-29 21:18 UTC, merged