ignore patterns like git
beam-cloud/beta9 pull request #538
Opened 2024-09-16 18:35 UTC by dleviminzi

This PR contains a small change to match patterns the way that git does when ignoring files to sync. It uses the `pathspec` library which was already one of our deps.

2024-09-17 17:14 UTC, luke-lombardi commented on sdk/src/beta9/sync.py
>      def _should_ignore(self, path: str) -> bool:
this seems reasonable, can we add a test case?

2024-09-17 23:55 UTC, luke-lombardi requested changes

2024-09-17 23:55 UTC, luke-lombardi commented on sdk/tests/test_filesyncer.py
> +class TestTaskQueue(TestCase):
should this be renamed?

2024-09-18 02:08 UTC, dleviminzi commented on sdk/tests/test_filesyncer.py
> +class TestTaskQueue(TestCase):
Ohp yeah

2024-09-18 02:53 UTC, luke-lombardi approved these changes
see last comment, otherwise good to merge

2024-09-18 02:53 UTC, luke-lombardi commented on sdk/tests/test_filesyncer.py
> +    def test_read_ignore_file(self):
nit-pick but I would clean up the spacing a bit on these tests, it's hard to read. otherwise good to go.

2024-09-18 13:26 UTC, merged