fix: fix any gpu scheduling
beam-cloud/beta9 pull request #609
Opened 2024-10-10 17:32 UTC by jsun-m

2024-10-11 12:38 UTC, dleviminzi approved these changes

2024-10-18 14:22 UTC, luke-lombardi approved these changes

2024-10-29 12:29 UTC, luke-lombardi requested changes
@jsun-m do we need to clean this one up now that we merged failover logic? maybe there's a cleaner way to do it now?

2024-10-30 20:30 UTC, luke-lombardi requested changes

2024-10-30 20:30 UTC, luke-lombardi commented on pkg/scheduler/scheduler.go
> +			if !validGpu {
can't we simplify this by saying if requiresGpu && isGpuWorker, we filter it in?

2025-02-07 19:42 UTC, closed without merging