Feat: VLLM abstraction
beam-cloud/beta9 pull request #665
Opened 2024-10-29 21:36 UTC by dleviminzi

This PR adds a VLLM abstraction. Every argument you can provide to `vllm serve ...` is supported and can be passed into the vllm class or as part of the `EngineConfig`. The defaults are the same as the ones in vllm's repo. 

Here is a simple example of how it used: 
```python
from beta9 import integrations

e = integrations.EngineConfig()
e.device = "cpu"

vllm_app = integrations.VLLM(name="vllm-abstraction-1", engine_config=e)
```

And we deploy with:
```bash
beta9 deploy app.py:vllm_app
```

Serve with:
```bash 
beta9 serve app.py:vllm_app
```

Below is an example of serving the above on my local machine. 

In order to get deploying/serving a class to work, I introduced a `set_handler` method. The deploy and serve code now checks if that message is present and uses it to set the user provided `app:obj`. Without this, we end up inspecting the sdk to generate the module:obj and that does not work. 

![Screenshot 2024-10-29 at 17 24 47](https://github.com/user-attachments/assets/6fe41b34-8829-4536-a478-9197035f5b05)

2024-10-29 22:20 UTC, dleviminzi commented on sdk/src/beta9/abstractions/integrations/vllm.py
> +app.get_fastapi_app()
I gotta fix this

2024-10-30 02:25 UTC, mernit commented
the `VLLM` class should be lowercase IMO

2024-10-30 18:59 UTC, luke-lombardi requested changes

2024-10-30 18:59 UTC, luke-lombardi commented on sdk/src/beta9/abstractions/integrations/vllm.py
> +class EngineConfig:
should we call this VLLMEngineConfig?

2024-10-30 18:59 UTC, luke-lombardi commented on sdk/src/beta9/cli/deployment.py
> +    # trying to get the handler
can you clean up this comment

2024-10-31 01:55 UTC, luke-lombardi requested changes
One last comment

2024-10-31 01:55 UTC, luke-lombardi commented on sdk/src/beta9/abstractions/integrations/vllm.py
> +class vllm(ASGI):
@mernit I actually think this should be Vllm or VLLM to distinguish it from the vllm module. Also it's not a decorator anyway (it's a class) and in python that's the standard way of formatting classes

2024-10-31 17:43 UTC, merged