feat: add multipart uploads and range downloads for volumes
beam-cloud/beta9 pull request #809
Opened 2024-12-23 14:46 UTC by nickpetrovic

- Add multipart volume uploads
- Add http range volume downloads
- Add fly.io juicefs gateway deployment
- Sort common commands by where they are defined
- Sort management commands alphabetically

Resolve BE-2133

2024-12-23 14:50 UTC, nickpetrovic commented on sdk/src/beta9/cli/main.py
> +os.environ["GRPC_VERBOSITY"] = os.getenv("GRPC_VERBOSITY") or "ERROR"
This should stop prevent the gRPC library logs from being emitted between builds and when thread/process pools are being used.

2024-12-23 14:52 UTC, nickpetrovic commented on sdk/src/beta9/channel.py
> +        channel.subscribe(*retry)
Setting this to True (the default) lets the channel reconnect on disconnects. It works really well from my testing.

2024-12-23 14:53 UTC, nickpetrovic commented on sdk/src/beta9/channel.py
> +        options.append(("grpc.secondary_user_agent", get_user_agent()))
The primary header is the grpclib and its version, the secondary is our CLI and its version.

2024-12-23 14:54 UTC, nickpetrovic commented on pkg/common/config.default.yaml
> +  secretKey:
TODO: Add region as an option so its not hardcoded to an empty string.

2024-12-23 14:55 UTC, nickpetrovic commented on pkg/abstractions/volume/multipart.go
> +		Region:       "-",
TODO: make region configurable

2024-12-23 14:56 UTC, nickpetrovic commented on deploy/fly-io/fly.toml
> +  cpu_kind = 'shared'
Did not see a difference between "performance" and "shared" in my testing. Could be different in production though.

2024-12-23 14:56 UTC, nickpetrovic commented on deploy/fly-io/fly.toml
In general, will probably want there to be a production version of this config so it has a rolling deployment strategy and different vm requirements.

2025-01-09 03:47 UTC, nickpetrovic commented on deploy/fly-io/fly.toml
> +  cpu_kind = 'shared'
An observation - localstack struggles hard when downloading files from the juicefs s3 gateway.

2025-01-09 03:52 UTC, nickpetrovic commented on sdk/src/beta9/cli/volume.py
> +)
Need to fallback to v1 if a file service is not configured.

2025-01-09 14:39 UTC, luke-lombardi requested changes
This is looking great! Left a couple minor nitpicks.

2025-01-09 14:39 UTC, luke-lombardi commented on deploy/fly-io/fly.toml
> +app = 'data-stage-beam-cloud'
wondering if this should be passed in as an arg or something? since this is our real staging deployment, not sure

2025-01-09 14:39 UTC, luke-lombardi commented on deploy/fly-io/start.sh
> +JUICEFS_BUFFER_SIZE=${JUICEFS_BUFFER_SIZE:-300}
where are these configs pulled from?

2025-01-09 14:39 UTC, luke-lombardi commented on pkg/abstractions/volume/multipart.go
> +	total_parts := math.Ceil(float64(in.FileSize) / float64(in.ChunkSize))
should fix the casing here and below `totalParts`, `uploadParts`

2025-01-09 14:41 UTC, nickpetrovic commented on pkg/abstractions/volume/multipart.go
> +	total_parts := math.Ceil(float64(in.FileSize) / float64(in.ChunkSize))
Updated!

2025-01-09 14:43 UTC, nickpetrovic commented on deploy/fly-io/start.sh
> +JUICEFS_BUFFER_SIZE=${JUICEFS_BUFFER_SIZE:-300}
Good call out. They're from fly's secrets. Let me add a README to this directory. There's a few steps that need to take place before you can call `fly deploy`.

2025-01-09 14:43 UTC, nickpetrovic commented on deploy/fly-io/fly.toml
> +app = 'data-stage-beam-cloud'
Good idea. That's probably possible, along with some of the VM configs. I'll look into this.

2025-01-09 15:30 UTC, nickpetrovic commented on deploy/fly-io/fly.toml
> +app = 'data-stage-beam-cloud'
Alright I modified the name to be "my-deployment". The reason is because fly will write the name of your deployment to this file even if you provide it as an argument to the CLI. I mentioned this in the README.

2025-01-09 15:30 UTC, nickpetrovic commented on deploy/fly-io/start.sh
> +JUICEFS_BUFFER_SIZE=${JUICEFS_BUFFER_SIZE:-300}
Added a README. Let me know what you think.

2025-01-09 16:46 UTC, mernit commented on sdk/src/beta9/cli/volume.py
> +    help="Copy contents to and from a volume.",
maybe update copy to include download here i.e. copy and download contents

2025-01-09 17:49 UTC, nickpetrovic commented on sdk/src/beta9/cli/volume.py
> +    help="Copy contents to and from a volume.",
Updated to this:

> Upload or download contents to or from a volume.

What do you think?

2025-01-09 20:04 UTC, luke-lombardi commented on deploy/fly-io/fly.toml
> +app = 'data-stage-beam-cloud'
LGTM

2025-01-09 20:05 UTC, luke-lombardi approved these changes

2025-01-09 21:15 UTC, luke-lombardi approved these changes

2025-01-09 21:35 UTC, merged