Feat: Add warm up endpoint to both endpoints and taskqueues
beam-cloud/beta9 pull request #813
Opened 2024-12-26 20:32 UTC by jsun-m

2024-12-30 22:31 UTC, jsun-m commented on pkg/abstractions/endpoint/http.go
> +	g.POST("/id/:stubId", auth.WithAuth(group.EndpointRequest))
uppercased these handlers to be consistent with other http handlers

2025-01-05 18:10 UTC, luke-lombardi requested changes

2025-01-05 18:10 UTC, luke-lombardi commented on pkg/abstractions/common/deployment.go
> +func ParseAndValidateDeploymentStubId(
@jsun-m once we add a test for this, I think it would be fine to add. Also not sure if this should live here or if it should live under http/apiv1? Since you're passing in the backendRepo and stuff anyway.

2025-01-07 22:38 UTC, jsun-m commented on pkg/abstractions/common/deployment.go
> +func ParseAndValidateDeploymentStubId(
I'm not sure where it would live in apiv1. The deployments.go file is completely diff

2025-01-07 23:59 UTC, luke-lombardi approved these changes

2025-01-08 00:01 UTC, merged